import 'package:flutter/material.dart';

class CustomColors extends ThemeExtension<CustomColors> {
  const CustomColors({
    required this.greyButton,
    required this.greyCircle,
    required this.redColor,
    required this.redDeleteColor,
    required this.vacationList,
    required this.greyText,
    required this.subTitle,
    required this.chipBackground,
    required this.chipText,
    required this.edittextBackProfile,
    required this.white,
    required this.messageLeft,
    required this.messageRight,
    required this.greyTab,
    required this.greyAmount,
    required this.redAmount,
    required this.greenAmount,
    required this.pendingAmount,
    required this.yellowStatus,
    required this.filterDivider,
    required this.referEarnColor,
    required this.closeAccountColor,
    required this.chatPrimary,
    required this.accentBlue,
    required this.profileBlue,
    required this.buddiesBackground,
    required this.buddiesCard,
    required this.buddiesBorder,
    required this.myButtonBgColor,
    required this.meetupButtonColor,
    required this.coachFacilityFavIconColor,
    required this.showTextColorForCancelAppointment,
    required this.bazaarTabBackground,
    required this.bazaarChatBackground,
    required this.meetupCreatorCard,
    required this.meetupParticipantCard,
    required this.meetupEmptyCard,
    required this.borderColor,
    required this.selectedGridItemColor,
    required this.lightBlueBGColor,
    required this.lightBlueBorderColor,
    required this.buttonBg,
    required this.greyBG,
    required this.buttonColorGrey,
    required this.hintTextColor,
    required this.textGray,
    required this.containerBG,
    required this.green,
    required this.darkRed,
    required this.onAccentText,
    required this.coachToolsBg,
    required this.getMovingTextColor,
    required this.homeScreenRewardBgColor,
    required this.blackAndWhiteColor,
    required this.homeScreenRewardTextColor,
    required this.homeScreenRewardButtonColor,
    required this.homeScreenRewardButtonTextColor,
    required this.appBackgroundColor,
    required this.bottomNavigationBarBackgroundColor,
    required this.promoteBusinessBorderColor,
    required this.progressDialogBackgroundColor,
  });

  final Color greyButton;
  final Color greyCircle;
  final Color redColor;
  final Color redDeleteColor;
  final Color vacationList;
  final Color greyText;
  final Color subTitle;
  final Color chipBackground;
  final Color chipText;
  final Color edittextBackProfile;
  final Color white;
  final Color messageLeft;
  final Color messageRight;
  final Color greyTab;
  final Color greyAmount;
  final Color redAmount;
  final Color greenAmount;
  final Color pendingAmount;
  final Color yellowStatus;
  final Color filterDivider;
  final Color referEarnColor;
  final Color closeAccountColor;
  final Color chatPrimary;
  final Color accentBlue;
  final Color profileBlue;
  final Color buddiesBackground;
  final Color buddiesCard;
  final Color buddiesBorder;
  final Color myButtonBgColor;
  final Color meetupButtonColor;
  final Color coachFacilityFavIconColor;
  final Color showTextColorForCancelAppointment;
  final Color bazaarTabBackground;
  final Color bazaarChatBackground;
  final Color meetupCreatorCard;
  final Color meetupParticipantCard;
  final Color meetupEmptyCard;
  final Color borderColor;
  final Color selectedGridItemColor;
  final Color lightBlueBGColor;
  final Color lightBlueBorderColor;
  final Color buttonBg;
  final Color greyBG;
  final Color buttonColorGrey;
  final Color hintTextColor;
  final Color textGray;
  final Color containerBG;
  final Color green;
  final Color darkRed;
  final Color onAccentText;
  final Color coachToolsBg;
  final Color getMovingTextColor;
  final Color homeScreenRewardBgColor;
  final Color blackAndWhiteColor;
  final Color homeScreenRewardTextColor;
  final Color homeScreenRewardButtonColor;
  final Color homeScreenRewardButtonTextColor;
  final Color appBackgroundColor;
  final Color bottomNavigationBarBackgroundColor;
  final Color promoteBusinessBorderColor;
  final Color progressDialogBackgroundColor;

  static const CustomColors light = CustomColors(
    greyButton: Color(0xFFEFEFEF),
    greyCircle: Color(0xFFE2E2E8),
    redColor: Color(0xFFFF0000),
    redDeleteColor: Color(0xFFEE2B2F),
    vacationList: Color(0xFF80B2C7),
    greyText: Color(0xFF818181),
    subTitle: Color(0xFF3A3A3A),
    chipBackground: Color(0xFFE1EDF2),
    chipText: Color(0xFF2B2B2B),
    edittextBackProfile: Color(0xFFD9D9D9),
    white: Color(0xFFFFFFFF),
    messageLeft: Color(0xFFC7DDE7),
    messageRight: Color(0xFFC7C7C7),
    greyTab: Color(0xFFF8F8F8),
    greyAmount: Color(0xFF656565),
    redAmount: Color(0xFFFF0000),
    greenAmount: Color(0xFF008000),
    pendingAmount: Color(0xFFB59800),
    yellowStatus: Color(0xFFE1B000),
    filterDivider: Color(0xFFE3E3E3),
    referEarnColor: Color(0xFF006590),
    closeAccountColor: Color(0xFFFC5555),
    chatPrimary: Color(0xFF2B5278),
    accentBlue: Color(0xFF006590),
    profileBlue: Color(0xFF3C80A8),
    buddiesBackground: Color(0xFFF5F5F5),
    buddiesCard: Color(0xFFF1F1F1),
    buddiesBorder: Color(0xFFCFCFCF),
    myButtonBgColor: Color(0xFF006590),
    meetupButtonColor: Color(0xFFED8000),
    coachFacilityFavIconColor: Color(0xFFF1F1F1),
    showTextColorForCancelAppointment: Color(0xFFFFFFFF),
    bazaarTabBackground: Color(0xFFD4EEF9),
    bazaarChatBackground: Color(0xFFEAF3F7),
    meetupCreatorCard: Color(0xFFFFFAEB),
    meetupParticipantCard: Color(0xFFEAF2F6),
    meetupEmptyCard: Color(0xFFEDEDED),
    borderColor: Color(0xFFE9E9E9),
    selectedGridItemColor: Color(0xFFEBF9FF),
    lightBlueBGColor: Color(0xFFD6F3FF),
    lightBlueBorderColor: Color(0xFFB4D9E9),
    buttonBg: Color(0xFFF2F2F2),
    greyBG: Color(0xFFDBDBDB),
    buttonColorGrey: Color(0xFFF6F6F6),
    hintTextColor: Color(0xFF878787),
    textGray: Color(0xFF737373),
    containerBG: Color(0xFFFBFBFB),
    green: Color(0xFF067421),
    darkRed: Color(0xFFA80000),
    onAccentText: Color(0xFFFFFFFF),
    coachToolsBg: Color(0xFFF7F7F7),
    getMovingTextColor: Color(0xFF000000),
    homeScreenRewardBgColor: Color(0xFF3396D3),
    blackAndWhiteColor: Color(0xFF000000),
    homeScreenRewardTextColor: Color(0xFF006590),
    homeScreenRewardButtonColor: Color(0xFF3396D3),
    homeScreenRewardButtonTextColor: Color(0xFFFFFFFF),
    appBackgroundColor: Color(0xFFFFFFFF),
    bottomNavigationBarBackgroundColor: Color(0xFFFFFFFF),
    promoteBusinessBorderColor: Color(0xFF3396D3),
    progressDialogBackgroundColor: Color(0xFFF0F7FF),
  );

  static const CustomColors dark = CustomColors(
    greyButton: Color(0xFF333333),
    greyCircle: Color(0xFF404040),
    redColor: Color(0xFFFF6B6B),
    redDeleteColor: Color(0xFFFF5252),
    vacationList: Color(0xFF4A90A4),
    greyText: Color(0xFFB0B0B0),
    subTitle: Color(0xFFD0D0D0),
    chipBackground: Color(0xFF2A3540),
    chipText: Color(0xFFD0D0D0),
    edittextBackProfile: Color(0xFF404040),
    white: Color(0xFF1E1E1E),
    messageLeft: Color(0xFF2A4A57),
    messageRight: Color(0xFF404040),
    greyTab: Color(0xFF2A2A2A),
    greyAmount: Color(0xFFB0B0B0),
    redAmount: Color(0xFFFF6B6B),
    greenAmount: Color(0xFF4CAF50),
    pendingAmount: Color(0xFFFFA726),
    yellowStatus: Color(0xFFFFD54F),
    filterDivider: Color(0xFF404040),
    referEarnColor: Color(0xFF006590),
    closeAccountColor: Color(0xFFFF5252),
    chatPrimary: Color(0xFF2B5278),
    accentBlue: Color(0xFF4FC3F7),
    profileBlue: Color(0xFF4FC3F7),
    buddiesBackground: Color(0xFF2A2A2A),
    buddiesCard: Color(0xFF333333),
    buddiesBorder: Color(0xFF404040),
    myButtonBgColor: Color(0xFF006590),
    meetupButtonColor: Color(0xFFFFB74D),
    coachFacilityFavIconColor: Color(0xFFFFFFFF),
    showTextColorForCancelAppointment: Color(0xFFFFFFFF),
    bazaarTabBackground: Color(0xFF2A3540),
    bazaarChatBackground: Color(0xFF2A2A2A),
    meetupCreatorCard: Color(0xFF3B3628),
    meetupParticipantCard: Color(0xFF2A3540),
    meetupEmptyCard: Color(0xFF2A2A2A),
    borderColor: Color(0xFF404040),
    selectedGridItemColor: Color(0xFF1E3A45),
    lightBlueBGColor: Color(0xFF102734),
    lightBlueBorderColor: Color(0xFF2F5E73),
    buttonBg: Color(0xFF2A2A2A),
    greyBG: Color(0xFF3A3A3A),
    buttonColorGrey: Color(0xFF333333),
    hintTextColor: Color(0xFFB0B0B0),
    textGray: Color(0xFFB0B0B0),
    containerBG: Color(0xFF1E1E1E),
    green: Color(0xFF4CAF50),
    darkRed: Color(0xFFE57373),
    onAccentText: Color(0xFFFFFFFF),
    coachToolsBg: Color(0xFF1F2937),
    getMovingTextColor: Color(0xFFFFFFFF),
    homeScreenRewardBgColor: Color(0xFF1F2937),
    blackAndWhiteColor: Color(0xFFFFFFFF),
    homeScreenRewardTextColor: Color(0xFF3396D3),
    homeScreenRewardButtonColor: Color(0xFF3396D3),
    homeScreenRewardButtonTextColor: Color(0xFFFFFFFF),
    appBackgroundColor: Color(0xFF111827),
    bottomNavigationBarBackgroundColor: Color(0xFF1F2937),
    promoteBusinessBorderColor: Color(0xFF3396D3),
    progressDialogBackgroundColor: Color(0xFF1A2A3D),
  );

  @override
  CustomColors copyWith({
    Color? greyButton,
    Color? greyCircle,
    Color? redColor,
    Color? redDeleteColor,
    Color? vacationList,
    Color? greyText,
    Color? subTitle,
    Color? chipBackground,
    Color? chipText,
    Color? edittextBackProfile,
    Color? white,
    Color? messageLeft,
    Color? messageRight,
    Color? greyTab,
    Color? greyAmount,
    Color? redAmount,
    Color? greenAmount,
    Color? pendingAmount,
    Color? yellowStatus,
    Color? filterDivider,
    Color? referEarnColor,
    Color? closeAccountColor,
    Color? chatPrimary,
    Color? accentBlue,
    Color? profileBlue,
    Color? buddiesBackground,
    Color? buddiesCard,
    Color? buddiesBorder,
    Color? myButtonBgColor,
    Color? meetupButtonColor,
    Color? coachFacilityFavIconColor,
    Color? showTextColorForCancelAppointment,
    Color? bazaarTabBackground,
    Color? bazaarChatBackground,
    Color? meetupCreatorCard,
    Color? meetupParticipantCard,
    Color? meetupEmptyCard,
    Color? borderColor,
    Color? selectedGridItemColor,
    Color? lightBlueBGColor,
    Color? lightBlueBorderColor,
    Color? buttonBg,
    Color? greyBG,
    Color? buttonColorGrey,
    Color? hintTextColor,
    Color? textGray,
    Color? containerBG,
    Color? green,
    Color? darkRed,
    Color? onAccentText,
    Color? coachToolsBg,
    Color? getMovingTextColor,
    Color? homeScreenRewardBgColor,
    Color? blackAndWhiteColor,
    Color? homeScreenRewardTextColor,
    Color? homeScreenRewardButtonColor,
    Color? homeScreenRewardButtonTextColor,
    Color? appBackgroundColor,
    Color? bottomNavigationBarBackgroundColor,
    Color? promoteBusinessBorderColor,
    Color? progressDialogBackgroundColor,
  }) {
    return CustomColors(
      greyButton: greyButton ?? this.greyButton,
      greyCircle: greyCircle ?? this.greyCircle,
      redColor: redColor ?? this.redColor,
      redDeleteColor: redDeleteColor ?? this.redDeleteColor,
      vacationList: vacationList ?? this.vacationList,
      greyText: greyText ?? this.greyText,
      subTitle: subTitle ?? this.subTitle,
      chipBackground: chipBackground ?? this.chipBackground,
      chipText: chipText ?? this.chipText,
      edittextBackProfile: edittextBackProfile ?? this.edittextBackProfile,
      white: white ?? this.white,
      messageLeft: messageLeft ?? this.messageLeft,
      messageRight: messageRight ?? this.messageRight,
      greyTab: greyTab ?? this.greyTab,
      greyAmount: greyAmount ?? this.greyAmount,
      redAmount: redAmount ?? this.redAmount,
      greenAmount: greenAmount ?? this.greenAmount,
      pendingAmount: pendingAmount ?? this.pendingAmount,
      yellowStatus: yellowStatus ?? this.yellowStatus,
      filterDivider: filterDivider ?? this.filterDivider,
      referEarnColor: referEarnColor ?? this.referEarnColor,
      closeAccountColor: closeAccountColor ?? this.closeAccountColor,
      chatPrimary: chatPrimary ?? this.chatPrimary,
      accentBlue: accentBlue ?? this.accentBlue,
      profileBlue: profileBlue ?? this.profileBlue,
      buddiesBackground: buddiesBackground ?? this.buddiesBackground,
      buddiesCard: buddiesCard ?? this.buddiesCard,
      buddiesBorder: buddiesBorder ?? this.buddiesBorder,
      myButtonBgColor: myButtonBgColor ?? this.myButtonBgColor,
      meetupButtonColor: meetupButtonColor ?? this.meetupButtonColor,
      coachFacilityFavIconColor: coachFacilityFavIconColor ?? this.coachFacilityFavIconColor,
      showTextColorForCancelAppointment: showTextColorForCancelAppointment ?? this.showTextColorForCancelAppointment,
      bazaarTabBackground: bazaarTabBackground ?? this.bazaarTabBackground,
      bazaarChatBackground: bazaarChatBackground ?? this.bazaarChatBackground,
      meetupCreatorCard: meetupCreatorCard ?? this.meetupCreatorCard,
      meetupParticipantCard: meetupParticipantCard ?? this.meetupParticipantCard,
      meetupEmptyCard: meetupEmptyCard ?? this.meetupEmptyCard,
      borderColor: borderColor ?? this.borderColor,
      selectedGridItemColor: selectedGridItemColor ?? this.selectedGridItemColor,
      lightBlueBGColor: lightBlueBGColor ?? this.lightBlueBGColor,
      lightBlueBorderColor: lightBlueBorderColor ?? this.lightBlueBorderColor,
      buttonBg: buttonBg ?? this.buttonBg,
      greyBG: greyBG ?? this.greyBG,
      buttonColorGrey: buttonColorGrey ?? this.buttonColorGrey,
      hintTextColor: hintTextColor ?? this.hintTextColor,
      textGray: textGray ?? this.textGray,
      containerBG: containerBG ?? this.containerBG,
      green: green ?? this.green,
      darkRed: darkRed ?? this.darkRed,
      onAccentText: onAccentText ?? this.onAccentText,
      coachToolsBg: coachToolsBg ?? this.coachToolsBg,
      getMovingTextColor: getMovingTextColor ?? this.getMovingTextColor,
      homeScreenRewardBgColor: homeScreenRewardBgColor ?? this.homeScreenRewardBgColor,
      blackAndWhiteColor: blackAndWhiteColor ?? this.blackAndWhiteColor,
      homeScreenRewardTextColor: homeScreenRewardTextColor ?? this.homeScreenRewardTextColor,
      homeScreenRewardButtonColor: homeScreenRewardButtonColor ?? this.homeScreenRewardButtonColor,
      homeScreenRewardButtonTextColor: homeScreenRewardButtonTextColor ?? this.homeScreenRewardButtonTextColor,
      appBackgroundColor: appBackgroundColor ?? this.appBackgroundColor,
      bottomNavigationBarBackgroundColor: bottomNavigationBarBackgroundColor ?? this.bottomNavigationBarBackgroundColor,
      promoteBusinessBorderColor: promoteBusinessBorderColor ?? this.promoteBusinessBorderColor,
      progressDialogBackgroundColor: progressDialogBackgroundColor ?? this.progressDialogBackgroundColor,
    );
  }

  @override
  CustomColors lerp(ThemeExtension<CustomColors>? other, double t) {
    if (other is! CustomColors) return this;
    return CustomColors(
      greyButton: Color.lerp(greyButton, other.greyButton, t)!,
      greyCircle: Color.lerp(greyCircle, other.greyCircle, t)!,
      redColor: Color.lerp(redColor, other.redColor, t)!,
      redDeleteColor: Color.lerp(redDeleteColor, other.redDeleteColor, t)!,
      vacationList: Color.lerp(vacationList, other.vacationList, t)!,
      greyText: Color.lerp(greyText, other.greyText, t)!,
      subTitle: Color.lerp(subTitle, other.subTitle, t)!,
      chipBackground: Color.lerp(chipBackground, other.chipBackground, t)!,
      chipText: Color.lerp(chipText, other.chipText, t)!,
      edittextBackProfile: Color.lerp(edittextBackProfile, other.edittextBackProfile, t)!,
      white: Color.lerp(white, other.white, t)!,
      messageLeft: Color.lerp(messageLeft, other.messageLeft, t)!,
      messageRight: Color.lerp(messageRight, other.messageRight, t)!,
      greyTab: Color.lerp(greyTab, other.greyTab, t)!,
      greyAmount: Color.lerp(greyAmount, other.greyAmount, t)!,
      redAmount: Color.lerp(redAmount, other.redAmount, t)!,
      greenAmount: Color.lerp(greenAmount, other.greenAmount, t)!,
      pendingAmount: Color.lerp(pendingAmount, other.pendingAmount, t)!,
      yellowStatus: Color.lerp(yellowStatus, other.yellowStatus, t)!,
      filterDivider: Color.lerp(filterDivider, other.filterDivider, t)!,
      referEarnColor: Color.lerp(referEarnColor, other.referEarnColor, t)!,
      closeAccountColor: Color.lerp(closeAccountColor, other.closeAccountColor, t)!,
      chatPrimary: Color.lerp(chatPrimary, other.chatPrimary, t)!,
      accentBlue: Color.lerp(accentBlue, other.accentBlue, t)!,
      profileBlue: Color.lerp(profileBlue, other.profileBlue, t)!,
      buddiesBackground: Color.lerp(buddiesBackground, other.buddiesBackground, t)!,
      buddiesCard: Color.lerp(buddiesCard, other.buddiesCard, t)!,
      buddiesBorder: Color.lerp(buddiesBorder, other.buddiesBorder, t)!,
      myButtonBgColor: Color.lerp(myButtonBgColor, other.myButtonBgColor, t)!,
      meetupButtonColor: Color.lerp(meetupButtonColor, other.meetupButtonColor, t)!,
      coachFacilityFavIconColor: Color.lerp(coachFacilityFavIconColor, other.coachFacilityFavIconColor, t)!,
      showTextColorForCancelAppointment: Color.lerp(showTextColorForCancelAppointment, other.showTextColorForCancelAppointment, t)!,
      bazaarTabBackground: Color.lerp(bazaarTabBackground, other.bazaarTabBackground, t)!,
      bazaarChatBackground: Color.lerp(bazaarChatBackground, other.bazaarChatBackground, t)!,
      meetupCreatorCard: Color.lerp(meetupCreatorCard, other.meetupCreatorCard, t)!,
      meetupParticipantCard: Color.lerp(meetupParticipantCard, other.meetupParticipantCard, t)!,
      meetupEmptyCard: Color.lerp(meetupEmptyCard, other.meetupEmptyCard, t)!,
      borderColor: Color.lerp(borderColor, other.borderColor, t)!,
      selectedGridItemColor: Color.lerp(selectedGridItemColor, other.selectedGridItemColor, t)!,
      lightBlueBGColor: Color.lerp(lightBlueBGColor, other.lightBlueBGColor, t)!,
      lightBlueBorderColor: Color.lerp(lightBlueBorderColor, other.lightBlueBorderColor, t)!,
      buttonBg: Color.lerp(buttonBg, other.buttonBg, t)!,
      greyBG: Color.lerp(greyBG, other.greyBG, t)!,
      buttonColorGrey: Color.lerp(buttonColorGrey, other.buttonColorGrey, t)!,
      hintTextColor: Color.lerp(hintTextColor, other.hintTextColor, t)!,
      textGray: Color.lerp(textGray, other.textGray, t)!,
      containerBG: Color.lerp(containerBG, other.containerBG, t)!,
      green: Color.lerp(green, other.green, t)!,
      darkRed: Color.lerp(darkRed, other.darkRed, t)!,
      onAccentText: Color.lerp(onAccentText, other.onAccentText, t)!,
      coachToolsBg: Color.lerp(coachToolsBg, other.coachToolsBg, t)!,
      getMovingTextColor: Color.lerp(getMovingTextColor, other.getMovingTextColor, t)!,
      homeScreenRewardBgColor: Color.lerp(homeScreenRewardBgColor, other.homeScreenRewardBgColor, t)!,
      blackAndWhiteColor: Color.lerp(blackAndWhiteColor, other.blackAndWhiteColor, t)!,
      homeScreenRewardTextColor: Color.lerp(homeScreenRewardTextColor, other.homeScreenRewardTextColor, t)!,
      homeScreenRewardButtonColor: Color.lerp(homeScreenRewardButtonColor, other.homeScreenRewardButtonColor, t)!,
      homeScreenRewardButtonTextColor: Color.lerp(homeScreenRewardButtonTextColor, other.homeScreenRewardButtonTextColor, t)!,
      appBackgroundColor: Color.lerp(appBackgroundColor, other.appBackgroundColor, t)!,
      bottomNavigationBarBackgroundColor: Color.lerp(bottomNavigationBarBackgroundColor, other.bottomNavigationBarBackgroundColor, t)!,
      promoteBusinessBorderColor: Color.lerp(promoteBusinessBorderColor, other.promoteBusinessBorderColor, t)!,
      progressDialogBackgroundColor: Color.lerp(progressDialogBackgroundColor, other.progressDialogBackgroundColor, t)!,
    );
  }
}
